import argparse
import logging
import re
from asyncio import Future, create_task, run
from pathlib import Path

from dotenv import load_dotenv
from group_terminal.server import ChatServer

from examples.chat.assistant import Service
from examples.utils import configure_logging
from group_sense import ConcurrentGroupReasoner, Decision, DefaultGroupReasonerFactory, Message, Response

logger = logging.getLogger(__name__)


class App:
    def __init__(self, host: str, port: int, reasoner_template_name: str):
        # --8<-- [start:integration-setup]
        # Reasoner setup
        template = self._load_reasoner_template(reasoner_template_name)
        self._factory = DefaultGroupReasonerFactory(system_prompt_template=template)
        self._reasoner = ConcurrentGroupReasoner(factory=self._factory)
        # --8<-- [end:integration-setup]

        # Chat server setup
        self._server = ChatServer(host=host, port=port)
        self._server.add_handler(self._handle_message)

        # Downstream service
        self._service = Service()

    @property
    def server(self):
        return self._server

    # --8<-- [start:integration-handler]
    async def _handle_message(self, content: str, sender: str):
        message = self._create_reasoner_message(content, sender)
        # Initiate reasoner processing in message arrival order
        # (guarantees equal internal and chat message ordering)
        future = self._reasoner.process(message)
        # Asynchronously await and process reasoner response
        create_task(self._handle_response(future, sender))

    async def _handle_response(self, future: Future[Response], sender: str):
        try:
            reasoner_response = await future
        except Exception:
            logger.exception("Reasoner error")
            return

        logger.debug(f"Reasoner decision: {reasoner_response.decision.value}")
        if reasoner_response.decision == Decision.IGNORE:
            return

        if not reasoner_response.query:
            logger.warning("Reasoner delegated without query")
            return

        try:
            # Run downstream assistant with query generated by reasoner
            logger.debug(f"Assistant query: {reasoner_response.query}")
            assistant_response = await self._service.run(reasoner_response.query, sender=sender)
        except Exception:
            logger.exception("Assistant error")
        else:
            logger.debug(f"Assistant response: {assistant_response}")

            if reasoner_response.receiver:
                # If reasoner set a dynamic receiver, @mention them in the chat message
                assistant_response = f"@{reasoner_response.receiver} {assistant_response}"

            message = Message(
                content=assistant_response,
                sender="system",
                receiver=reasoner_response.receiver,
            )

            # Add response message to reasoner
            # (needed for concurrent reasoning)
            self._reasoner.append(message)

            # Send response to chat clients
            await self._server.send_message(message.content, sender=message.sender)

    # --8<-- [end:integration-handler]

    def _create_reasoner_message(self, content: str, sender: str) -> Message:
        if match := re.match(r"^@(\S+)\s*(.*)", content):
            # content started with an @mention, which is extracted and set as receiver
            return Message(content=match.group(2), sender=sender, receiver=match.group(1))
        return Message(content=content, sender=sender, receiver=None)

    def _load_reasoner_template(self, name: str) -> str:
        with open(Path(__file__).parent.parent / "prompts" / "concurrent" / f"{name}.md") as f:
            return f.read()


async def main(args):
    app = App(
        host=args.host,
        port=args.port,
        reasoner_template_name=args.reasoner_template,
    )

    await app.server.start()
    await app.server.join()


if __name__ == "__main__":
    configure_logging()
    load_dotenv()

    parser = argparse.ArgumentParser()
    parser.add_argument("--reasoner-template", type=str, default="general_assist")
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8723)

    run(main(args=parser.parse_args()))
